name: fashion-mnist
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.8
  - pip
  - pip:
    - numpy>=1.21.0,<1.27.0
    - streamlit>=1.28.0
    - tensorflow==2.15.1
    - Pillow>=9.0.0
